# Generated by Django 3.0.5 on 2021-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceman',
            name='otp',
            field=models.CharField(default='1111', max_length=6),
        ),
    ]
