# Generated by Django 3.1.7 on 2021-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_serviceman_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(default='_', max_length=200)),
                ('serviceman_id', models.CharField(default='_', max_length=200)),
                ('cost', models.FloatField(default=0.0)),
                ('ispaid', models.BooleanField(default=False)),
                ('department', models.CharField(default='_', max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=-1)),
                ('feedback', models.CharField(default='_', max_length=500)),
            ],
        ),
    ]
