# Generated by Django 3.1.7 on 2021-04-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210419_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='otp',
            field=models.IntegerField(default=1111),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doa', models.DateField()),
                ('purpose', models.CharField(blank=True, default='', max_length=100)),
                ('remark_from_staff', models.CharField(blank=True, default='', max_length=200)),
                ('remark_from_user', models.CharField(blank=True, default='', max_length=200)),
                ('requestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.request')),
            ],
            options={
                'ordering': ['doa'],
                'unique_together': {('requestid', 'doa')},
            },
        ),
    ]
