# Generated by Django 3.1.7 on 2021-04-12 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_request_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='descr',
            field=models.CharField(default='_', max_length=500),
        ),
        migrations.AddField(
            model_name='request',
            name='doa',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
