# Generated by Django 3.1.7 on 2021-04-17 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210413_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='serviceman',
            name='otp',
        ),
    ]
