# Generated by Django 3.1.7 on 2021-04-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210420_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['doa']},
        ),
        migrations.AlterField(
            model_name='appointments',
            name='requestid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.request'),
        ),
    ]
