# Generated by Django 3.1.7 on 2021-04-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210420_1333'),
        ('shop', '0011_auto_20210420_1853'),
    ]

    operations = [
    ]
