# Generated by Django 3.0.5 on 2021-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_merge_20210420_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='otp',
            field=models.IntegerField(default=1111),
        ),
    ]
